// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

import './coordinate_dto.dart';

part 'geometry_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class GeometryDto {
  final String type;
  // final List<CoordinateDto> coordinates;
  final List<double> coordinates;

  const GeometryDto({
    required this.type,
    required this.coordinates,
  });

  factory GeometryDto.fromJson(Map<String, dynamic> json) =>
      _$GeometryDtoFromJson(json);
  Map<String, dynamic> toJson() => _$GeometryDtoToJson(this);
}
