// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'properties_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PropertiesDto {
  final double mag;
  final String place;
  final int time;
  final int updated;
  final int? tz;
  final String url;
  final String detail;
  final int? felt;
  final double? cdi;
  final double? mmi;
  final String? alert;
  final String status;
  final int tsunami;
  final int sig;
  final String net;
  final String code;
  final String ids;
  final String sources;
  final String types;
  final int? nst;
  final double? dmin;
  final double rms;
  final double? gap;
  final String magType;
  final String type;
  final String title;

  // https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php

  const PropertiesDto({
    required this.mag,
    required this.place,
    required this.time,
    required this.updated,
    this.tz,
    required this.url,
    required this.detail,
    this.felt,
    this.cdi,
    this.mmi,
    this.alert,
    required this.status,
    required this.tsunami,
    required this.sig,
    required this.net,
    required this.code,
    required this.ids,
    required this.sources,
    required this.types,
    this.nst,
    this.dmin,
    required this.rms,
    this.gap,
    required this.magType,
    required this.type,
    required this.title,
  });

  factory PropertiesDto.fromJson(Map<String, dynamic> json) =>
      _$PropertiesDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PropertiesDtoToJson(this);
}
