// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'metadata_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class MetadataDto {
  final int generated;
  final String url;
  final String title;
  final String api;
  final int count;
  final int status;

  const MetadataDto({
    required this.generated,
    required this.url,
    required this.title,
    required this.api,
    required this.count,
    required this.status,
  });

  factory MetadataDto.fromJson(Map<String, dynamic> json) =>
      _$MetadataDtoFromJson(json);
  Map<String, dynamic> toJson() => _$MetadataDtoToJson(this);
}
